datasources:
  - engine: pandas
    version: 2.0
    name: my_demo_datasource
    assets:
      - type: file
        name: my_demo_file_asset
        file_path: great_expectations/zep/my_file.csv
        delimiter: "|"
      - type: other
        name: another_asset
        food: "pizza"
