datasources:
  my_pg_ds:
    type: postgres
    name: my_pg_ds
    connection_str: "postgres://foo.bar"
    assets:
      my_table_asset_wo_splitters:
        type: table
        name: my_table_asset_wo_splitters
        table_name: my_table
      with_splitters:
        type: table
        name: with_splitters
        table_name: another_table
        column_splitter:
              method_name: foobar_it
              column_name: my_column
              name: my_splitter
              template_params:
                - alpha
                - bravo
                - charlie
  my_demo_pd_datasource:
    type: pandas
    name: my_demo_pd_datasource
    assets:
      my_demo_file_asset:
        type: file
        name: my_demo_file_asset
        delimiter: "|"
        file_path: "great_expectations/zep/my_file.csv"