datasources:
  my_pg_ds:
    type: postgres
    name: my_pg_ds
    connection_str: "postgres://foo.bar"
    assets:
      my_pg_table_asset:
        type: table
        name: my_pg_table_asset
        table_name: my_table
