datasources:
  my_demo_datasource:
    type: postgres
    name: real_pg_ds
    connection_str: "postgres://foo.bar"
    assets:
      my_demo_file_asset:
        type: file
        name: my_demo_file_asset # TODO: remove name
        file_path: great_expectations/zep/my_file.csv
        delimiter: "|"
      another_asset:
        type: other
        name: another_asset # TODO: remove name
        food: "pizza"
