datasources:
  my_demo_datasource:
    engine: pandas
    execution_engine: pandas
    name: my_demo_datasource
    assets:
      my_demo_file_asset:
        type: file
        name: my_demo_file_asset
