datasources:
  taxi_datasource:
    version: 2.0
    engine: pandas
    connection_str: "foo//bar"
    assets:
      yellow_trip_data:
        type: file
        base_directory: "great_expectations/zap"
        separators: \t
        has_headers: false
      yellow_trip_data_but_sql:
        type: sql
        query: "SELECT * FROM TAXI"
      # sql_but_wrong:
      #   type: sql
      #   weary: "SELECT * FROM TAXI"
